services:
  mlflow:
    image: python:3.11-slim
    container_name: datathon_mlflow
    ports:
      - "5002:5000"
    volumes:
      - mlflow_data:/mlflow
    networks:
      - datathon_net
    working_dir: /mlflow
    entrypoint: /bin/bash
    command:
      - -c
      - "pip install mlflow==2.10.2 --quiet && mkdir -p /mlflow/artifacts && mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:////mlflow/mlflow.db --default-artifact-root /mlflow/artifacts"

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: datathon_fastapi
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - ENVIRONMENT=local
    depends_on:
      - mlflow
    networks:
      - datathon_net

volumes:
  mlflow_data:
    driver: local

networks:
  datathon_net:
    driver: bridge
