FROM ubuntu:26.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-venv \
    build-essential \
    git \
    curl \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN python3 -m pip install --upgrade pip setuptools wheel || true && \
    python3 -m venv /opt/venv && \
    /opt/venv/bin/pip install --upgrade pip && \
    /opt/venv/bin/pip install --no-cache-dir mlflow sqlalchemy alembic psycopg2-binary boto3
ENV PATH="/opt/venv/bin:$PATH"

COPY . /app
RUN chmod +x /app/deploy/mlflow-entrypoint.sh

EXPOSE 5000

ENTRYPOINT ["/app/deploy/mlflow-entrypoint.sh"]
